<?PHP
/* Runnable checks for bay_map.php — the drive bay assignment store (plan 047).
     php tests/bay_map_test.php  ->  "bay_map: all pass" (exit 0)

   WHY THIS MATTERS MORE THAN THE OTHER STORES. Everything else this plugin
   persists can be regenerated by re-reading the hardware; a bay map cannot. It
   is a person walking to the rack and typing in where each drive physically
   sits. Losing it silently — to a shrunk grid, a key-shape change, or a config
   write that resets its own dimensions — means doing that walk again, so each
   of those is a case below.

   Everything here runs through injected temp paths: no /boot, no HTTP, no
   hardware. */

require_once __DIR__ . '/../source/usr/local/emhttp/plugins/hbaviewer/bay_map.php';

$fails = 0;
function check(string $name, bool $ok): void {
    global $fails;
    echo ($ok ? "PASS  " : "FAIL  ") . $name . "\n";
    if (!$ok) $fails++;
}

$dir  = sys_get_temp_dir() . '/hbav_baymap_' . getmypid();
@mkdir($dir, 0755, true);
$path = "$dir/bay_map.json";
$cfg  = "$dir/hbaviewer.cfg";
$reset = function () use ($path) { @unlink($path); };

/* ── 1. Read degrades, never fatals ──────────────────────────────────────── */
$reset();
check('missing file reads as empty', bay_map_read($path) === []);
file_put_contents($path, 'not json at all');
check('corrupt file reads as empty', bay_map_read($path) === []);
file_put_contents($path, '"a string"');
check('non-array JSON reads as empty', bay_map_read($path) === []);
/* Per entry, not just the top level. Every consumer indexes $pos['row'], so
   one bad value in a hand-edited file used to be a TypeError that took the
   whole tab down — the map that cannot be regenerated is exactly the one
   somebody is most likely to have edited by hand. */
file_put_contents($path, '{"c0:p1": "x", "c0:p2": 7, "c0:p3": {"row": 1}, "c0:p4": {"row": 1, "col": 2}}');
check('malformed entries drop, good ones survive',
      bay_map_read($path) === ['c0:p4' => ['row' => 1, 'col' => 2]]);

/* Clear (the "Clear map" button) writes an empty map. json_encode([]) emits
   "[]", a JSON *array* rather than an object — so this checks the file it
   leaves behind still reads back as an empty map instead of tripping the
   corrupt-file path or, worse, fataling on the tab that has to render it. */
$reset();
bay_map_write(['c0:p1' => ['row' => 0, 'col' => 0], 'c0:p2' => ['row' => 1, 'col' => 1]], $path);
bay_map_write([], $path);
check('clearing empties the map', bay_map_read($path) === []);
check('a cleared map is still valid on disk',
      is_file($path) && bay_map_read($path) === [] && json_decode((string) file_get_contents($path), true) === []);

/* Undo. The confirm dialog was the only guard Clear had and it was not enough —
   a misclick got through it and took a real map with it. These pin the parts
   that make the recovery actually work when someone needs it. */
$reset();
@unlink("$path.bak");
$full = ['c0:p1' => ['row' => 0, 'col' => 0], 'c0:p2' => ['row' => 1, 'col' => 1]];
bay_map_write($full, $path);
check('no undo offered before anything destructive', !bay_map_has_backup($path));
bay_map_backup($path);
bay_map_write([], $path);          // what the clear action does
check('undo is offered after a clear', bay_map_has_backup($path));
check('the map really was cleared', bay_map_read($path) === []);
check('undo restores every placement', bay_map_restore($path) && bay_map_read($path) === $full);
/* One-shot: a second undo must not silently re-apply an old map over edits the
   person has made since. */
check('undo is consumed by using it', !bay_map_has_backup($path));
check('a second undo reports nothing to do', bay_map_restore($path) === false);
check('the restored map survived the second attempt', bay_map_read($path) === $full);
/* Backing up an ALREADY-cleared map would overwrite the good backup with the
   state about to be regretted — clear twice and the undo is worthless. */
bay_map_backup($path);
bay_map_write([], $path);
bay_map_backup($path);             // second clear, nothing worth saving
bay_map_restore($path);
check('a second clear does not destroy the undo', bay_map_read($path) === $full);
@unlink("$path.bak");

/* Restore-from-paste. The text comes off somebody's clipboard, so this is a
   trust boundary and every rejection below is load-bearing. */
$san = bay_map_sanitize(['c0:p1' => ['row' => 0, 'col' => 0],
                         'c1:h3' => ['row' => 2, 'col' => 1]], 6, 4);
check('a good paste is kept whole',
      $san['map'] === ['c0:p1' => ['row' => 0, 'col' => 0], 'c1:h3' => ['row' => 2, 'col' => 1]]
      && $san['skipped'] === 0);
/* Without the key check a crafted paste writes arbitrary object keys onto the
   boot flash — this is the reason the function exists. */
$evil = bay_map_sanitize(['../../etc/passwd' => ['row' => 0, 'col' => 0],
                          'c0:p1' => ['row' => 0, 'col' => 1]], 6, 4);
check('a bogus key is refused, the good one survives',
      $evil['map'] === ['c0:p1' => ['row' => 0, 'col' => 1]] && $evil['skipped'] === 1);
// A bay outside the CURRENT grid would be stored and never rendered.
$out = bay_map_sanitize(['c0:p1' => ['row' => 99, 'col' => 0],
                         'c0:p2' => ['row' => 0, 'col' => 99],
                         'c0:p3' => ['row' => -1, 'col' => 0]], 6, 4);
check('positions outside the grid are dropped', $out['map'] === [] && $out['skipped'] === 3);
/* Two drives in one bay: the map renders one per bay, so the loser would be in
   the file and invisible on screen — stored, unfindable, and pointing whoever
   reads it at the wrong slot. */
$dup = bay_map_sanitize(['c0:p1' => ['row' => 1, 'col' => 1],
                         'c0:p2' => ['row' => 1, 'col' => 1]], 6, 4);
check('two drives cannot share a bay', count($dup['map']) === 1 && $dup['skipped'] === 1);
check('malformed entries are counted, not fataled',
      bay_map_sanitize(['c0:p1' => 'nope', 'c0:p2' => ['row' => 1], 'c0:p3' => ['row' => 'x', 'col' => 'y']],
                       6, 4) === ['map' => [], 'skipped' => 3]);
check('an empty paste is an empty map', bay_map_sanitize([], 6, 4) === ['map' => [], 'skipped' => 0]);
/* Copy -> paste has to survive the trip unchanged, or the backup is not one. */
$rt = ['c0:p0' => ['row' => 0, 'col' => 0], 'c1:x1Ah2' => ['row' => 3, 'col' => 2]];
$rtOut = bay_map_sanitize(json_decode(json_encode($rt), true), 6, 4);
check('a copied map round-trips through JSON intact', $rtOut['map'] === $rt && $rtOut['skipped'] === 0);

/* ── 2. Round-trip ───────────────────────────────────────────────────────── */
$reset();
bay_map_set('c0:p14', 2, 1, $path);
bay_map_set('c0:p15', 0, 0, $path);
$m = bay_map_read($path);
check('assign round-trips', ($m['c0:p14'] ?? null) === ['row' => 2, 'col' => 1]);
check('two drives coexist', count($m) === 2);
bay_map_set('c0:p14', null, null, $path);
check('unassign removes only its own key', array_keys(bay_map_read($path)) === ['c0:p15']);
// Re-assigning an existing key moves it rather than duplicating it.
bay_map_set('c0:p15', 3, 2, $path);
check('re-assign moves in place', bay_map_read($path) === ['c0:p15' => ['row' => 3, 'col' => 2]]);

/* ── 3. Shrinking the grid returns the drives it displaced ───────────────── */
$reset();
bay_map_set('c0:p1', 0, 0, $path);   // survives
bay_map_set('c0:p2', 5, 0, $path);   // row beyond a 4-row grid
bay_map_set('c0:p3', 0, 3, $path);   // col beyond a 2-col grid
$dropped = bay_map_prune_to_dims(4, 2, $path);
sort($dropped);
check('prune returns every displaced key', $dropped === ['c0:p2', 'c0:p3']);
check('prune keeps the ones that fit', array_keys(bay_map_read($path)) === ['c0:p1']);
check('prune removes the displaced ones from the store',
      !isset(bay_map_read($path)['c0:p2']) && !isset(bay_map_read($path)['c0:p3']));
// The boundary itself: a 4x2 grid has rows 0-3 and cols 0-1, so row 3 stays.
$reset();
bay_map_set('c0:p1', 3, 1, $path);
check('prune keeps the last in-grid position', bay_map_prune_to_dims(4, 2, $path) === []);
check('prune writes nothing when nothing moved', bay_map_read($path) === ['c0:p1' => ['row' => 3, 'col' => 1]]);

/* ── 4. Identity key: the s/h letter is load-bearing ─────────────────────── */
check('storcli drive keys on its slot', bay_map_key(0, ['slot' => '252/14', 'port' => '0', 'serial' => 'X']) === 'c0:s252/14');
check('a drive with no enclosure keys on the bare slot', bay_map_key(0, ['slot' => '3']) === 'c0:s3');
check('lsiutil drive keys on its phy',  bay_map_key(0, ['phy' => 2, 'os_name' => '/dev/sdb']) === 'c0:h2');
check('controller index is part of the key', bay_map_key(3, ['slot' => '252/14']) === 'c3:s252/14');
/* Issue #15: Connected Port Number is the CONTROLLER's port, and a SAS9305-16i
   reports 0 for every drive behind path0. Keying on it made one assignment
   place a dozen drives. Slot is per-drive; the port must not come back. */
check('the port is no longer an identity at all', bay_map_key(0, ['port' => '14']) === null);
$p0 = bay_map_key(0, ['slot' => '252/3', 'port' => '0']);
$p1 = bay_map_key(0, ['slot' => '252/4', 'port' => '0']);
check('two drives sharing port 0 get different keys', $p0 !== $p1 && $p0 !== null);
/* Slot 14 and PHY 14 are different physical positions. If the two shared a
   namespace, a box that switched backend would place a drive in the wrong bay
   — the one failure this store cannot recover from, because nothing on the
   machine knows the assignment was ever wrong. */
check('slot and phy never collide', bay_map_key(0, ['slot' => '2']) !== bay_map_key(0, ['phy' => 2]));
check('a drive with neither is unplaceable', bay_map_key(0, ['serial' => 'X']) === null);
check('an empty slot is unplaceable', bay_map_key(0, ['slot' => '']) === null);
/* The slot reaches a JSON object key on the boot flash, so it is checked
   against the grammar rather than trusted -- a payload that ever carried
   something else there must produce "unplaceable", not a new key shape. */
foreach (['../../etc', '1/2/3', '3"', '99999'] as $bad) {
    check("a slot of '$bad' is unplaceable", bay_map_key(0, ['slot' => $bad]) === null);
}
// A drive carrying both (no backend emits this today) must pick one and stay
// on it — flipping between them across releases would orphan every assignment.
check('phy wins when a drive somehow has both', bay_map_key(0, ['phy' => 1, 'slot' => '9']) === 'c0:h1');
/* Plan 052: an expander numbers its own PHYs from 0, same as the HBA, so
   "phy 8" alone cannot tell two expander-attached drives apart -- let alone
   an expander-attached drive from a direct-attached one on the same numbers.
   Three drives, same controller, same phy, three different expanders (one of
   them "no expander" i.e. direct-attached) must produce three distinct keys. */
check('direct-attached key is unchanged -- the no-migration promise',
      bay_map_key(0, ['phy' => 8]) === 'c0:h8');
$k1 = bay_map_key(0, ['phy' => 8, 'expander' => '']);
$k2 = bay_map_key(0, ['phy' => 8, 'expander' => '500304801AAAAA1F']);
$k3 = bay_map_key(0, ['phy' => 8, 'expander' => '500304801BBBBB2F']);
check('same phy, three different expanders -> three distinct keys',
      $k1 !== $k2 && $k2 !== $k3 && $k1 !== $k3);
check('direct-attached (empty expander) still keys as c0:h8', $k1 === 'c0:h8');

/* ── 5. Key validation — this is a trust boundary ────────────────────────── */
check('valid storcli key accepted', bay_map_key_valid('c0:s252/14'));
check('valid bare-slot key accepted', bay_map_key_valid('c0:s3'));
check('valid lsiutil key accepted', bay_map_key_valid('c12:h3'));
// Still accepted so a pre-#15 map survives long enough to be migrated, even
// though nothing emits it any more.
check('a pre-#15 port key is still readable', bay_map_key_valid('c0:p14'));
foreach (['', 'c0:x1', 'c0:p', 'p14', 'c0:p14 ', '../../etc/passwd', 'c0:p14"}', 'c99999:p1',
          'c0:s', 'c0:s1/', 'c0:s/1', 'c0:s1/2/3', 'c0:s252/14 '] as $bad) {
    check("rejects '" . $bad . "'", !bay_map_key_valid($bad));
}
/* ── 4b. The #15 migration: port keys carried onto slot keys ─────────────── */
$mp = tempnam(sys_get_temp_dir(), 'bmm');
// One controller: ports 1 and 2 are unique (migratable), port 0 is shared by
// two drives (the collision itself, not migratable).
$payload = ['controllers' => [['drives' => [
    ['port' => '1', 'slot' => '252/1'],
    ['port' => '2', 'slot' => '252/2'],
    ['port' => '0', 'slot' => '252/3'],
    ['port' => '0', 'slot' => '252/4'],
]]]];
bay_map_write(['c0:p1' => ['row' => 0, 'col' => 0],
               'c0:p2' => ['row' => 1, 'col' => 1],
               'c0:p0' => ['row' => 2, 'col' => 2]], $mp);
check('migration reports what it moved', bay_map_migrate_ports($payload, $mp) === 2);
$m = bay_map_read($mp);
check('an unambiguous port keeps its position under the slot key',
      ($m['c0:s252/1'] ?? null) === ['row' => 0, 'col' => 0]
   && ($m['c0:s252/2'] ?? null) === ['row' => 1, 'col' => 1]);
check('the migrated port keys are gone', !isset($m['c0:p1'], $m['c0:p2']));
/* The colliding entry was never about one drive, so there is nothing to carry
   it onto. Left in place rather than deleted: it matches no drive (all four
   now key on slot), so every one of them lands back in the tray, which is
   this store's stated way of surfacing a key that stopped matching. */
check('an ambiguous port entry is left alone, not guessed at',
      ($m['c0:p0'] ?? null) === ['row' => 2, 'col' => 2]);
check('running it again is a no-op', bay_map_migrate_ports($payload, $mp) === 0);

// A drive that is not in the payload at all -- controller failed to enumerate,
// or the disk is out for the afternoon. Its placement must survive.
bay_map_write(['c0:p7' => ['row' => 3, 'col' => 3]], $mp);
check('an absent drive keeps its placement', bay_map_migrate_ports($payload, $mp) === 0
   && bay_map_read($mp) === ['c0:p7' => ['row' => 3, 'col' => 3]]);

// Already placed under the new key: the person has re-assigned it since, and
// the stale port entry must not overwrite that.
bay_map_write(['c0:p1' => ['row' => 0, 'col' => 0], 'c0:s252/1' => ['row' => 5, 'col' => 5]], $mp);
bay_map_migrate_ports($payload, $mp);
check('a position set since the upgrade wins over the stale port key',
      bay_map_read($mp)['c0:s252/1'] === ['row' => 5, 'col' => 5]);

// An lsiutil map has no port keys and must not be touched or rewritten.
bay_map_write(['c0:h3' => ['row' => 1, 'col' => 1]], $mp);
check('an lsiutil map is left entirely alone', bay_map_migrate_ports($payload, $mp) === 0);
@unlink($mp);

// Plan 052: the expander-disambiguated shape, and its one canonical spelling.
check('valid expander-disambiguated key accepted', bay_map_key_valid('c0:x500304801AAAAA1Fh8'));
check("rejects lower-case hex -- bay_map_read() matches keys byte-for-byte",
      !bay_map_key_valid('c0:x500304801aaaaa1fh8'));

/* ── 6. Dimensions: writing them must not wipe the rest of the config ─────
   lsi_config_write() writes EVERY schema key and defaults anything absent, so
   a naive two-key write resets HBA_PORT and every SHOW_* toggle. Nudging the
   grid size must not turn off someone's tabs. */
lsi_config_write(['HBA_PORT' => 4, 'ALERT_THRESHOLD' => 96, 'SHOW_PERF' => 0] + lsi_config_read($cfg), $cfg);
bay_map_dims_set(8, 3, $cfg);
$after = lsi_config_read($cfg);
check('dims persist', bay_map_dims($cfg) === ['rows' => 8, 'cols' => 3]);
check('dims write preserves HBA_PORT',        $after['HBA_PORT'] === 4);
check('dims write preserves ALERT_THRESHOLD', $after['ALERT_THRESHOLD'] === 96);
check('dims write preserves SHOW_PERF off',   $after['SHOW_PERF'] === 0);
// Out-of-range values clamp exactly as a Settings-page value would.
bay_map_dims_set(99, 0, $cfg);
check('dims clamp to schema', bay_map_dims($cfg) === ['rows' => 12, 'cols' => 1]);
// Defaults are the maintainer's chassis: 6 rows x 4 columns.
check('defaults are 6x4', bay_map_dims("$dir/nonexistent.cfg") === ['rows' => 6, 'cols' => 4]);

/* ── 7. The lock ─────────────────────────────────────────────────────────────
   It persists, because the accident it prevents is a stray click on a map
   somebody built by walking to the rack — and a lock that forgets itself on
   reload prevents nothing. A new install is unlocked: there is nothing to
   protect until the map exists. */
check('a fresh install is unlocked', bay_map_locked("$dir/nonexistent.cfg") === false);
bay_map_lock_set(true, $cfg);
check('lock persists', bay_map_locked($cfg) === true);
$afterLock = lsi_config_read($cfg);
check('locking preserves the grid size', $afterLock['BAY_ROWS'] === 12 && $afterLock['BAY_COLS'] === 1);
check('locking preserves HBA_PORT',      $afterLock['HBA_PORT'] === 4);
bay_map_lock_set(false, $cfg);
check('unlock persists', bay_map_locked($cfg) === false);
/* The lock guards the store, not the store's own functions: bay_map_set() is
   the primitive the dispatch calls AFTER its lock check, so it must stay
   unconditional — a lock enforced in two places drifts. */
bay_map_lock_set(true, $cfg);
bay_map_set('c0:p7', 1, 1, $path);
check('the store primitive itself is not lock-aware', isset(bay_map_read($path)['c0:p7']));

array_map('unlink', glob("$dir/*") ?: []);
@rmdir($dir);



echo $fails === 0 ? "bay_map: all pass\n" : "bay_map: $fails FAILED\n";
exit($fails === 0 ? 0 : 1);
