<?PHP
/* Runnable checks for bay_map.php — the drive bay assignment store (plan 047).
     php tests/bay_map_test.php  ->  "bay_map: all pass" (exit 0)

   WHY THIS MATTERS MORE THAN THE OTHER STORES. Everything else this plugin
   persists can be regenerated by re-reading the hardware; a bay map cannot. It
   is a person walking to the rack and typing in where each drive physically
   sits. Losing it silently — to a shrunk grid, a key-shape change, or a config
   write that resets its own dimensions — means doing that walk again, so each
   of those is a case below.

   Everything here runs through injected temp paths: no /boot, no HTTP, no
   hardware. */

require_once __DIR__ . '/../source/usr/local/emhttp/plugins/hbaviewer/bay_map.php';

$fails = 0;
function check(string $name, bool $ok): void {
    global $fails;
    echo ($ok ? "PASS  " : "FAIL  ") . $name . "\n";
    if (!$ok) $fails++;
}

$dir  = sys_get_temp_dir() . '/hbav_baymap_' . getmypid();
@mkdir($dir, 0755, true);
$path = "$dir/bay_map.json";
$cfg  = "$dir/hbaviewer.cfg";
$reset = function () use ($path) { @unlink($path); };

/* ── 1. Read degrades, never fatals ──────────────────────────────────────── */
$reset();
check('missing file reads as empty', bay_map_read($path) === []);
file_put_contents($path, 'not json at all');
check('corrupt file reads as empty', bay_map_read($path) === []);
file_put_contents($path, '"a string"');
check('non-array JSON reads as empty', bay_map_read($path) === []);
/* Per entry, not just the top level. Every consumer indexes $pos['row'], so
   one bad value in a hand-edited file used to be a TypeError that took the
   whole tab down — the map that cannot be regenerated is exactly the one
   somebody is most likely to have edited by hand. */
file_put_contents($path, '{"c0:p1": "x", "c0:p2": 7, "c0:p3": {"row": 1}, "c0:p4": {"row": 1, "col": 2}}');
check('malformed entries drop, good ones survive',
      bay_map_read($path) === ['c0:p4' => ['row' => 1, 'col' => 2]]);

/* Clear (the "Clear map" button) writes an empty map. json_encode([]) emits
   "[]", a JSON *array* rather than an object — so this checks the file it
   leaves behind still reads back as an empty map instead of tripping the
   corrupt-file path or, worse, fataling on the tab that has to render it. */
$reset();
bay_map_write(['c0:p1' => ['row' => 0, 'col' => 0], 'c0:p2' => ['row' => 1, 'col' => 1]], $path);
bay_map_write([], $path);
check('clearing empties the map', bay_map_read($path) === []);
check('a cleared map is still valid on disk',
      is_file($path) && bay_map_read($path) === [] && json_decode((string) file_get_contents($path), true) === []);

/* ── 2. Round-trip ───────────────────────────────────────────────────────── */
$reset();
bay_map_set('c0:p14', 2, 1, $path);
bay_map_set('c0:p15', 0, 0, $path);
$m = bay_map_read($path);
check('assign round-trips', ($m['c0:p14'] ?? null) === ['row' => 2, 'col' => 1]);
check('two drives coexist', count($m) === 2);
bay_map_set('c0:p14', null, null, $path);
check('unassign removes only its own key', array_keys(bay_map_read($path)) === ['c0:p15']);
// Re-assigning an existing key moves it rather than duplicating it.
bay_map_set('c0:p15', 3, 2, $path);
check('re-assign moves in place', bay_map_read($path) === ['c0:p15' => ['row' => 3, 'col' => 2]]);

/* ── 3. Shrinking the grid returns the drives it displaced ───────────────── */
$reset();
bay_map_set('c0:p1', 0, 0, $path);   // survives
bay_map_set('c0:p2', 5, 0, $path);   // row beyond a 4-row grid
bay_map_set('c0:p3', 0, 3, $path);   // col beyond a 2-col grid
$dropped = bay_map_prune_to_dims(4, 2, $path);
sort($dropped);
check('prune returns every displaced key', $dropped === ['c0:p2', 'c0:p3']);
check('prune keeps the ones that fit', array_keys(bay_map_read($path)) === ['c0:p1']);
check('prune removes the displaced ones from the store',
      !isset(bay_map_read($path)['c0:p2']) && !isset(bay_map_read($path)['c0:p3']));
// The boundary itself: a 4x2 grid has rows 0-3 and cols 0-1, so row 3 stays.
$reset();
bay_map_set('c0:p1', 3, 1, $path);
check('prune keeps the last in-grid position', bay_map_prune_to_dims(4, 2, $path) === []);
check('prune writes nothing when nothing moved', bay_map_read($path) === ['c0:p1' => ['row' => 3, 'col' => 1]]);

/* ── 4. Identity key: the p/h letter is load-bearing ─────────────────────── */
check('storcli drive keys on its port', bay_map_key(0, ['port' => '14', 'serial' => 'X']) === 'c0:p14');
check('lsiutil drive keys on its phy',  bay_map_key(0, ['phy' => 2, 'os_name' => '/dev/sdb']) === 'c0:h2');
check('controller index is part of the key', bay_map_key(3, ['port' => '14']) === 'c3:p14');
/* Port 14 and PHY 14 are different physical positions. If the two shared a
   namespace, a box that switched backend would place a drive in the wrong bay
   — the one failure this store cannot recover from, because nothing on the
   machine knows the assignment was ever wrong. */
check('port and phy never collide', bay_map_key(0, ['port' => '2']) !== bay_map_key(0, ['phy' => 2]));
check('a drive with neither is unplaceable', bay_map_key(0, ['serial' => 'X']) === null);
check('an empty port is unplaceable', bay_map_key(0, ['port' => '']) === null);
// A drive carrying both (no backend emits this today) must pick one and stay
// on it — flipping between them across releases would orphan every assignment.
check('phy wins when a drive somehow has both', bay_map_key(0, ['phy' => 1, 'port' => '9']) === 'c0:h1');
/* Plan 052: an expander numbers its own PHYs from 0, same as the HBA, so
   "phy 8" alone cannot tell two expander-attached drives apart -- let alone
   an expander-attached drive from a direct-attached one on the same numbers.
   Three drives, same controller, same phy, three different expanders (one of
   them "no expander" i.e. direct-attached) must produce three distinct keys. */
check('direct-attached key is unchanged -- the no-migration promise',
      bay_map_key(0, ['phy' => 8]) === 'c0:h8');
$k1 = bay_map_key(0, ['phy' => 8, 'expander' => '']);
$k2 = bay_map_key(0, ['phy' => 8, 'expander' => '500304801AAAAA1F']);
$k3 = bay_map_key(0, ['phy' => 8, 'expander' => '500304801BBBBB2F']);
check('same phy, three different expanders -> three distinct keys',
      $k1 !== $k2 && $k2 !== $k3 && $k1 !== $k3);
check('direct-attached (empty expander) still keys as c0:h8', $k1 === 'c0:h8');

/* ── 5. Key validation — this is a trust boundary ────────────────────────── */
check('valid storcli key accepted', bay_map_key_valid('c0:p14'));
check('valid lsiutil key accepted', bay_map_key_valid('c12:h3'));
foreach (['', 'c0:x1', 'c0:p', 'p14', 'c0:p14 ', '../../etc/passwd', 'c0:p14"}', 'c99999:p1'] as $bad) {
    check("rejects '" . $bad . "'", !bay_map_key_valid($bad));
}
// Plan 052: the expander-disambiguated shape, and its one canonical spelling.
check('valid expander-disambiguated key accepted', bay_map_key_valid('c0:x500304801AAAAA1Fh8'));
check("rejects lower-case hex -- bay_map_read() matches keys byte-for-byte",
      !bay_map_key_valid('c0:x500304801aaaaa1fh8'));

/* ── 6. Dimensions: writing them must not wipe the rest of the config ─────
   lsi_config_write() writes EVERY schema key and defaults anything absent, so
   a naive two-key write resets HBA_PORT and every SHOW_* toggle. Nudging the
   grid size must not turn off someone's tabs. */
lsi_config_write(['HBA_PORT' => 4, 'ALERT_THRESHOLD' => 96, 'SHOW_PERF' => 0] + lsi_config_read($cfg), $cfg);
bay_map_dims_set(8, 3, $cfg);
$after = lsi_config_read($cfg);
check('dims persist', bay_map_dims($cfg) === ['rows' => 8, 'cols' => 3]);
check('dims write preserves HBA_PORT',        $after['HBA_PORT'] === 4);
check('dims write preserves ALERT_THRESHOLD', $after['ALERT_THRESHOLD'] === 96);
check('dims write preserves SHOW_PERF off',   $after['SHOW_PERF'] === 0);
// Out-of-range values clamp exactly as a Settings-page value would.
bay_map_dims_set(99, 0, $cfg);
check('dims clamp to schema', bay_map_dims($cfg) === ['rows' => 12, 'cols' => 1]);
// Defaults are the maintainer's chassis: 6 rows x 4 columns.
check('defaults are 6x4', bay_map_dims("$dir/nonexistent.cfg") === ['rows' => 6, 'cols' => 4]);

/* ── 7. The lock ─────────────────────────────────────────────────────────────
   It persists, because the accident it prevents is a stray click on a map
   somebody built by walking to the rack — and a lock that forgets itself on
   reload prevents nothing. A new install is unlocked: there is nothing to
   protect until the map exists. */
check('a fresh install is unlocked', bay_map_locked("$dir/nonexistent.cfg") === false);
bay_map_lock_set(true, $cfg);
check('lock persists', bay_map_locked($cfg) === true);
$afterLock = lsi_config_read($cfg);
check('locking preserves the grid size', $afterLock['BAY_ROWS'] === 12 && $afterLock['BAY_COLS'] === 1);
check('locking preserves HBA_PORT',      $afterLock['HBA_PORT'] === 4);
bay_map_lock_set(false, $cfg);
check('unlock persists', bay_map_locked($cfg) === false);
/* The lock guards the store, not the store's own functions: bay_map_set() is
   the primitive the dispatch calls AFTER its lock check, so it must stay
   unconditional — a lock enforced in two places drifts. */
bay_map_lock_set(true, $cfg);
bay_map_set('c0:p7', 1, 1, $path);
check('the store primitive itself is not lock-aware', isset(bay_map_read($path)['c0:p7']));

array_map('unlink', glob("$dir/*") ?: []);
@rmdir($dir);

echo $fails === 0 ? "bay_map: all pass\n" : "bay_map: $fails FAILED\n";
exit($fails === 0 ? 0 : 1);
